services:
  api:
    image: taggyappbackend
    ports:
      - 8080:80
    build:
      context: .
      dockerfile: TaggyAppBackend.Api/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: "http://+:80"
    depends_on:
      - postgres
    networks:
        - api-network
  postgres:
    image: postgres:16.0
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: taggyapp
      POSTGRES_PASSWORD: changeme
      POSTGRES_DB: taggyappdb 
    networks:
        - api-network
networks:
    api-network:
