name: Publish

on:
  workflow_dispatch:
  push:
    paths:
    - 'TaggyAppBackend/**'
    branches:
    - develop
  pull_request:
    paths:
    - 'TaggyAppBackend/**'
    branches:
    - master

env:
  AZURE_WEBAPP_NAME: 'taggyapp'
  AZURE_WEBAPP_PACKAGE_PATH: './TaggyAppBackend/publish'

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
          
      - name: Restore
        run: dotnet restore ./TaggyAppBackend/TaggyAppBackend.sln
        
      - name: Build
        run: dotnet build ./TaggyAppBackend/TaggyAppBackend.sln --configuration Release --no-restore

      - name: Test
        run: dotnet test ./TaggyAppBackend/TaggyAppBackend.sln --no-build --verbosity normal
        
      - name: Publish
        run: dotnet publish ./TaggyAppBackend/TaggyAppBackend.sln --configuration Release --no-build --output '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}'

      - name: Deployment
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_BACKEND_PUBLISH_PROFILE }}
          package: "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}"